#!/bin/sh

# $FreeBSD$
#
# PROVIDE: bazarr
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# bazarr_enable:    Set to YES to enable bazarr
#            Default: NO
# bazarr_user:    The user account used to run the bazarr daemon.
#            This is optional, however do not specifically set this to an
#            empty string as this will cause the daemon to run as root.
#            Default: media
# bazarr_group:    The group account used to run the bazarr daemon.
#            This is optional, however do not specifically set this to an
#            empty string as this will cause the daemon to run with group wheel.
#            Default: media
# bazarr_data_dir:    Directory where bazarr configuration
#            data is stored.
#            Default: /var/db/bazarr

. /etc/rc.subr
name=bazarr
rcvar=${name}_enable
load_rc_config $name

: ${bazarr_enable:="NO"}
: ${bazarr_user:="bazarr"}
: ${bazarr_group:="bazarr"}
: ${bazarr_data_dir:="/config"}

pidfile="${bazarr_data_dir}/bazarr.pid"
command="/usr/sbin/daemon"
procname="/usr/local/bin/python3"
command_args="-f -p ${pidfile} ${procname} /usr/local/share/bazarr/bazarr.py --config ${bazarr_data_dir}"

start_precmd=bazarr_precmd
bazarr_precmd()
{
	export XDG_CONFIG_HOME=${bazarr_data_dir}
        export GIT_PYTHON_REFRESH=quiet

	if [ ! -d ${bazarr_data_dir} ]; then
		install -d -o ${bazarr_user} ${bazarr_data_dir}
	fi
}

bazarr_postcmd()
{
	killall -u ${bazarr_user} -9
}

run_rc_command "$1"